<?php
    /** @var \Elementary\Webp\Block\Picture $block */
    $width = ($block->getWidth()) ? ' width="' . $block->getWidth() . '"' : '';
    $height = ($block->getHeight()) ? ' height="' . $block->getHeight() . '"' : '';
    $altText = ($block->getAltText()) ? ' alt="' . $block->getAltText() . '"' : '';
    $class = ($block->getClass()) ? ' class="' . $block->getClass() . ' lazy"' : 'lazy';
?>
<?php if ($block->getDebug()) : ?>
    <!-- <?= $block->getOriginalTag() ?> -->
<?php endif; ?>
<picture <?= $altText ?>>
    <source type="image/webp" data-srcset="<?= $block->getWebpImage() ?>">
    <source type="<?= $block->getOriginalImageType() ?>" data-srcset="<?= $block->getOriginalImage() ?>">
    <?= $block->getOriginalTag() ?>
</picture>
