#!/bin/bash
echo "Correcting filesystem ownerships..."

if [ -z "$1" ]; then
  sh rootnotty chown -R www:www /var/www/
else
  sh rootnotty chown -R www:www /var/www/html/$1
fi

echo "Filesystem ownerships corrected."
