#!/bin/bash
echo "Correcting filesystem permissions..."
APP_PATH='/var/www/html/src/script'
if [ -z "$1" ]; then
  sh $APP_PATH/clinotty find src/var src/vendor src/pub/static src/pub/media src/app/etc -type f -exec chmod u+w {} \;
  sh $APP_PATH/clinotty find src/var src/vendor src/pub/static src/pub/media src/app/etc -type d -exec chmod u+w {} \;
  sh $APP_PATH/clinotty chmod u+x src/bin/magento
else
  sh $APP_PATH/clinotty find $1 -type f -exec chmod u+w {} \;
  sh $APP_PATH/clinotty find $1 -type d -exec chmod u+w {} \;
fi

echo "Filesystem permissions corrected."
